#main:
#    resource: "@MainBundle/Controller/"
#    type:     annotation
#    prefix:   /

landing:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"