<?php

namespace MainBundle\Repository;

/**
 * RicettaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RicettaRepository extends \Doctrine\ORM\EntityRepository
{
}
