main_landing:
    path:     /landing
    defaults: { _controller: MainBundle:Landing:landing }

main_home:
    path:     /
    defaults: { _controller: MainBundle:Home:home }

main_plate:
    path:     /plate/{id}
    defaults: { _controller: MainBundle:Plate:plate }

main_plate_crea:
    path:     /plate/crea/{id}
    defaults: { _controller: MainBundle:Plate:create }



main_plate_lista:
    path:     /plate/list
    defaults: { _controller: MainBundle:Plate:list }

main_ricetta:
    path:     /ricetta/{id}
    defaults: { _controller: MainBundle:Ricetta:ricetta }

main_ricetta_crea:
    path:     /ricetta/crea
    defaults: { _controller: MainBundle:Ricetta:create }

main_ricetta_modifica:
    path:     /ricetta/{id}/edit
    defaults: { _controller: MainBundle:Ricetta:edit }

main_ricetta_delete:
    path:     /ricetta/{id}/delete
    defaults: { _controller: MainBundle:Ricetta:delete }

main_ricette_lista:
    path:     /ricetta/list
    defaults: { _controller: MainBundle:Ricetta:list }

main_user:
    path:     /user
    defaults: { _controller: MainBundle:User:user }

main_user_modifica:
    path:     /user/edit
    defaults: { _controller: MainBundle:User:edit }

main_user_delete:
    path:     /user/delete
    defaults: { _controller: MainBundle:User:delete }

main_user_lista:
    path:     /user/list
    defaults: { _controller: MainBundle:User:list }
